import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="p-6 lg:p-8">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex gap-6 list-none">
          <li>
            <Link href={"/"}>Home</Link>
          </li>
          |
          <li>
            <Link href={"/about"}>About</Link>
          </li>
          |
          <li>
            <Link href={"/blogs"}>Blogs</Link>
          </li>
        </nav>
        <hr className="bg-black h-[2px]" />
        <main className="mt-10 space-y-5">{children}</main>
      </body>
    </html>
  );
}
