import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Navbar from "./components/Navbar";
import AuthProvider from "@/services/AuthProvider";
// import { usePathname } from "next/navigation";
// import getPathname from "@/lib/getPathname";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: {
    default: "Home | Next Hero",
    template: "%s | Next Hero",
  },
  description: "Explore Next JS as a beginner.",
  keywords: "Explore Next JS as a beginner".split(" "),
};
// export const metadata = {
//   title: "Explore Next JS",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathName = "";
  // const pathName = getPathname();
  // console.log(pathName);

  return (
    <html lang="en" className="p-6 lg:p-8">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <Navbar></Navbar>
          <hr className="bg-black h-[2px]" />
          <main className="mt-10 space-y-5">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
